# Custom Language File for Launcher Customizer

[ejs.app]
title = "Deltaria | Launcher"

[ejs.landing]
mediaGitHubURL = "https://deltaria.fr"
mediaXURL = "https://x.com/DeltariaS32853"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@Deltaria-k4b"
mediaDiscordURL = "https://discord.gg/yFbapk6xjT"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Deltaria"
welcomeDescription = "Deltaria est un projet Minecraft basés sur les événèements de tout type, proposés par BxFouco  & Tennôsei."
welcomeDescCTA = ""
